---
driver:
  name: vagrant
  network:
    - [ "private_network" , {ip : "192.168.34.37"} ]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: default
    data_bags_path: test/fixtures/default/data_bags
    run_list:
      - recipe[tomcat::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
